parameters:
  name: ''
  vmImage: ''
  dependsOn: 'WindowsBuild'
  artifactName: 'akkaBuild'
  scriptFileName: ''
  scriptArgs: 'all'
  outputDirectory: ''
  timeoutInMinutes: 120

jobs:
  - job: ${{ parameters.name }}
    dependsOn:  ${{ parameters.dependsOn }}
    timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
      - task: DownloadPipelineArtifact@0
        inputs:
          artifactName: ${{ parameters.artifactName }}
          targetPath: $(System.DefaultWorkingDirectory)
      - task: Bash@3 
        displayName: Linux / OSX Build
        inputs:
          filePath: ${{ parameters.scriptFileName }}
          arguments: ${{ parameters.scriptArgs }}
        continueOnError: true
        condition: in( variables['Agent.OS'], 'Linux', 'Darwin' )
      # Windows
      - task: BatchScript@1
        displayName: Windows Build
        inputs:
          filename: ${{ parameters.scriptFileName }}
          arguments: ${{ parameters.scriptArgs }}
        continueOnError: true
        condition: eq( variables['Agent.OS'], 'Windows_NT' )
      - task: PublishTestResults@2
        inputs:
          testRunner: VSTest
          testResultsFiles: '**/*.trx' #TestResults folder usually
          testRunTitle: ${{ parameters.name }}
          mergeTestResults: true
      - task: CopyFiles@2
        displayName: 'Copy TestResults'
        inputs:
          sourceFolder: ${{ parameters.outputDirectory }}
          contents: '*'
          targetFolder: $(Build.ArtifactStagingDirectory)
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: ${{ parameters.name }}
      - script: 'echo 1>&2'
        failOnStderr: true
        displayName: 'If above is partially succeeded, then fail'
        condition: eq(variables['Agent.JobStatus'], 'SucceededWithIssues')